@server=http://localhost:4004
@username=alice
@password=

### ServiceDocument
GET {{server}}/odata/v4/employee

### Service Document Metadata
GET {{server}}/odata/v4/employee/$metadata

### GET EmployeeSet
# @name EmployeeSet_GET
GET {{server}}/odata/v4/employee/EmployeeSet
Authorization: Basic {{username}}:{{password}}

### Employees whose name starts with ‘S’
GET {{server}}/odata/v4/employee/EmployeeSet?$filter=startswith(nameFirst,'S')


### Top 2 Employee order by salary
GET {{server}}/odata/v4/employee/EmployeeSet?$top=2&orderby=salaryAmount


### EmployeeSet CREATE with salary < 50000 and USD
# @name EmployeeSet_POST
POST {{server}}/odata/v4/employee/EmployeeSet
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "14642026-b621-4c06-965b-af08033e7d03",
  "nameFirst": "nameFirst-14642026",
  "nameMiddle": "nameMiddle-14642026",
  "nameLast": "nameLast-14642026",
  "nameInitials": "nameInitials-14642026",
  "gender": "M",
  "language": "6",
  "phoneNumber": "phoneNumber-14642026",
  "email": "email-14642026",
  "loginName": "ame-14642026",
  "currency": {
    "code": "921"
  },
  "salaryAmount": 30881.2,
  "accountNumber": "tNumber-14642026",
  "bankId": "14642026",
  "bankName": "bankName-14642026"
}


### EmployeeSet
# @name EmployeeSet_PATCH
PATCH {{server}}/odata/v4/employee/EmployeeSet/14642026-b621-4c06-965b-af08033e7d03
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "14642026-b621-4c06-965b-af08033e7d03",
  "nameFirst": "nameFirst-14642026",
  "nameMiddle": "nameMiddle-14642026",
  "nameLast": "nameLast-14642026",
  "nameInitials": "nameInitials-14642026",
  "gender": "M",
  "language": "6",
  "phoneNumber": "phoneNumber-14642026",
  "email": "email-14642026",
  "loginName": "ame-14642026",
  "currency": {
    "code": "921"
  },
  "salaryAmount": 13271881.2,
  "accountNumber": "tNumber-14642026",
  "bankId": "14642026",
  "bankName": "bankName-14642026"
}


### EmployeeSet
# @name EmployeeSet_DELETE
DELETE {{server}}/odata/v4/employee/EmployeeSet/14642026-b621-4c06-965b-af08033e7d03
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Currencies
# @name Currencies_GET
GET {{server}}/odata/v4/employee/Currencies
Authorization: Basic {{username}}:{{password}}
